### ISSUE TITLE
Morning Section Team(Desmond-Johnson-Berkay-Rex)

### ISSUE THREAD

**Issue by Owusu-Desmond** [rex-9/Landsbetween#2]

**Comment by ifzyy** [comment]
You have done a great project here 

- Looks very nice
- Responsive
However, kindly take this into consideration 
The Home button on the about page isn't working as expected kindly look into it

**Comment by Owusu-Desmond** [comment]
You should add hover effect like ` cursor: pointer `on the top navigation icons and  texts
